scalar Date
scalar DateTime

type Query {
    findAllUsers: [User!]!
    findAllGroceries: [GroceryListItem!]!
    findGroceriesByTitle(title: String!): [GroceryListItem!]!
    findGroceryById(id: ID!): GroceryListItem!
}

type Mutation {
    login(dto: AuthDto!): ID!
    signup(dto: AuthDto!): ID!
    createGrocery(dto: CreateGroceryDto!): GroceryListItem!
    updateGrocery(id: ID!, dto: UpdateGroceryDto!): GroceryListItem!
    deleteGrocery(id: ID!): GroceryListItem!
}

input AuthDto {
    email: String!
    password: String!
}